name: turing_assessment_getx
description: Turing assessment project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  responsive_builder: ^0.4.3
  get: ^4.6.5
  get_storage: ^2.0.3
  local_auth: ^2.1.3
  flutter_svg_provider: ^1.0.3
  extended_image: ^6.3.4
  dio: ^4.0.6
  google_fonts: ^3.0.1
  cached_network_image: any
  loading_indicator: ^3.1.0
  carousel_slider: ^4.2.1
  dotted_line: ^3.1.0
  easy_splash_screen: ^1.0.4
  flutter_statusbarcolor_ns: ^0.5.0
  flutter_form_builder: ^7.7.0
  form_builder_validators: ^8.4.0
  connectivity_plus: ^3.0.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  fade_shimmer: ^2.2.0
  firebase_core: ^2.4.1
  firebase_analytics: ^10.1.0
  swipeable_tile: ^2.0.0+3
  intl: ^0.17.0
  flutter_advanced_switch: ^3.0.1
  flutter_easyloading: ^3.0.5
  flutter_icons:
    git:
      url: https://github.com/Sayed-Siam123/flutter-icons-master.git
      ref: master

  adaptive_theme: ^3.1.1
  webview_flutter: ^3.0.4
  loggy: ^2.0.3
  flutter_datetime_picker: ^1.5.1
  url_launcher: ^6.1.7
  flutter_screenutil: ^5.6.0
  data_table_2: ^2.3.10
  uuid: any
  google_maps_flutter: ^2.2.3
  geocoding: ^2.0.5


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_automation: ^2.0.0
  flutter_launcher_icons: ^0.11.0
  flutter_app_name: ^0.1.1


  flutter_lints: ^2.0.1
  device_preview:
    git:
      url: https://github.com/monkeydaichan/flutter_device_preview.git
      path: device_preview
      ref: master


dependency_overrides:
  platform: ^3.1.0
  flutter_math_fork: ^0.6.3+1
  permission_handler: ^10.2.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
